# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'select_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(600, 400)
        self.scroll_custem = QtWidgets.QSlider(Dialog)
        self.scroll_custem.setGeometry(QtCore.QRect(50, 170, 450, 150))
        self.scroll_custem.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scroll_custem.setMaximum(10)
        self.scroll_custem.setSingleStep(1)
        self.scroll_custem.setOrientation(QtCore.Qt.Horizontal)
        self.scroll_custem.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.scroll_custem.setObjectName("scroll_custem")
        self.lbl_douong = QtWidgets.QLabel(Dialog)
        self.lbl_douong.setGeometry(QtCore.QRect(150, 0, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_douong.setFont(font)
        self.lbl_douong.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.lbl_douong.setObjectName("lbl_douong")
        self.bt_ok = QtWidgets.QPushButton(Dialog)
        self.bt_ok.setGeometry(QtCore.QRect(460, 330, 120, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt_ok.setFont(font)
        self.bt_ok.setObjectName("bt_ok")
        self.bt_cancel = QtWidgets.QPushButton(Dialog)
        self.bt_cancel.setGeometry(QtCore.QRect(320, 330, 120, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt_cancel.setFont(font)
        self.bt_cancel.setObjectName("bt_cancel")
        self.lbl_custem = QtWidgets.QLabel(Dialog)
        self.lbl_custem.setGeometry(QtCore.QRect(540, 220, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lbl_custem.setFont(font)
        self.lbl_custem.setObjectName("lbl_custem")
        self.lbl_name = QtWidgets.QLabel(Dialog)
        self.lbl_name.setGeometry(QtCore.QRect(20, 340, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lbl_name.setFont(font)
        self.lbl_name.setText("")
        self.lbl_name.setObjectName("lbl_name")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 60, 531, 121))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radio_kd = QtWidgets.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radio_kd.setFont(font)
        self.radio_kd.setChecked(True)
        self.radio_kd.setObjectName("radio_kd")
        self.horizontalLayout.addWidget(self.radio_kd)
        self.radio_id = QtWidgets.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radio_id.setFont(font)
        self.radio_id.setObjectName("radio_id")
        self.horizontalLayout.addWidget(self.radio_id)
        self.radio_nd = QtWidgets.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radio_nd.setFont(font)
        self.radio_nd.setObjectName("radio_nd")
        self.horizontalLayout.addWidget(self.radio_nd)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lbl_douong.setText(_translate("Dialog", "NƯỚC CAM"))
        self.bt_ok.setText(_translate("Dialog", "OK"))
        self.bt_cancel.setText(_translate("Dialog", "CANCEL"))
        self.lbl_custem.setText(_translate("Dialog", "0"))
        self.radio_kd.setText(_translate("Dialog", "Không đường"))
        self.radio_id.setText(_translate("Dialog", "Ít đường"))
        self.radio_nd.setText(_translate("Dialog", "Nhiều đường"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
