# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ask.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 200)
        Form.setMaximumSize(QtCore.QSize(400, 200))
        Form.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.scroll = QtWidgets.QScrollBar(Form)
        self.scroll.setGeometry(QtCore.QRect(20, 50, 351, 61))
        self.scroll.setMaximumSize(QtCore.QSize(400, 80))
        self.scroll.setAutoFillBackground(True)
        self.scroll.setMinimum(50)
        self.scroll.setMaximum(100)
        self.scroll.setProperty("value", 90)
        self.scroll.setOrientation(QtCore.Qt.Horizontal)
        self.scroll.setObjectName("scroll")
        self.lb1 = QtWidgets.QLabel(Form)
        self.lb1.setGeometry(QtCore.QRect(30, 10, 101, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lb1.setFont(font)
        self.lb1.setObjectName("lb1")
        self.lb_scroll = QtWidgets.QLabel(Form)
        self.lb_scroll.setGeometry(QtCore.QRect(110, 10, 51, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lb_scroll.setFont(font)
        self.lb_scroll.setObjectName("lb_scroll")
        self.bt_ok = QtWidgets.QPushButton(Form)
        self.bt_ok.setGeometry(QtCore.QRect(10, 150, 121, 41))
        self.bt_ok.setObjectName("bt_ok")
        self.bt_nor = QtWidgets.QPushButton(Form)
        self.bt_nor.setGeometry(QtCore.QRect(270, 150, 121, 41))
        self.bt_nor.setObjectName("bt_nor")
        self.bt_tt = QtWidgets.QPushButton(Form)
        self.bt_tt.setGeometry(QtCore.QRect(140, 150, 121, 41))
        self.bt_tt.setObjectName("bt_tt")
        self.lb2 = QtWidgets.QLabel(Form)
        self.lb2.setGeometry(QtCore.QRect(210, 10, 81, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lb2.setFont(font)
        self.lb2.setObjectName("lb2")
        self.lb3 = QtWidgets.QLabel(Form)
        self.lb3.setGeometry(QtCore.QRect(290, 10, 51, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lb3.setFont(font)
        self.lb3.setObjectName("lb3")
        self.lb_scroll_2 = QtWidgets.QLabel(Form)
        self.lb_scroll_2.setGeometry(QtCore.QRect(150, 10, 31, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lb_scroll_2.setFont(font)
        self.lb_scroll_2.setObjectName("lb_scroll_2")
        self.lb_scroll_3 = QtWidgets.QLabel(Form)
        self.lb_scroll_3.setGeometry(QtCore.QRect(330, 10, 31, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lb_scroll_3.setFont(font)
        self.lb_scroll_3.setObjectName("lb_scroll_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lb1.setText(_translate("Form", "Coffee"))
        self.lb_scroll.setText(_translate("Form", "100"))
        self.bt_ok.setText(_translate("Form", "OK"))
        self.bt_nor.setText(_translate("Form", "MẶC ĐỊNH"))
        self.bt_tt.setText(_translate("Form", "THÔNG THƯỜNG"))
        self.lb2.setText(_translate("Form", "Đường"))
        self.lb3.setText(_translate("Form", "100"))
        self.lb_scroll_2.setText(_translate("Form", "%"))
        self.lb_scroll_3.setText(_translate("Form", "%"))
